version: '3.8'

services:
  web:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet
    restart: unless-stopped


networks:
  webnet:
    driver: bridge

volumes:
  db_data:
